name: "VMImage CI"

on:
  push:
    branches: [ "master", "103lts" ]
    paths: 
      - 'avocado/utils/vmimage.py'
      - 'selftests/utils/vmimage.py'
  pull_request:
    branches: [ "master", "103lts" ]
    paths: 
      - 'avocado/utils/vmimage.py'
      - 'selftests/utils/vmimage.py'

jobs:
  vmimge-test-coverage:

    name: Code Coverage
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - run: echo "Job triggered by a ${{ github.event_name }} event on branch is ${{ github.ref }} in repository is ${{ github.repository }}, runner on ${{ runner.os }}"
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        run: pip install -r requirements-dev.txt
      - name: Avocado build
        run: python setup.py develop --user
      - name: Run script
        run: ./selftests/run_coverage --select=vmimage
      - name: Push results to codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
      -  run: echo "🥑 This job's status is ${{ job.status }}."
